name: Generic Issue
description: Create a new issue
title: '<title>'
labels: [Needs Triage]

body:
  - type: textarea
    attributes:
      label: Issue description
      description: Provide a clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce (if applicable)
      description: List the steps to reproduce the issue, if applicable.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or information about the issue.
    validations:
      required: false
